/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary:    '#2EA7E0',
        secondary:  '#F5DFDB',
        accent:     '#BAEF62',
        error:      '#FE3843',
        warning:    '#FFDB1C',
        success:    '#17DB4E',
        'text-primary':   '#000000',
        'text-secondary': '#6E6E6E',
        'text-tertiary':  '#ADADAD',
        'text-inverse':   '#FFFFFF',
        'text-disabled':  '#C8C8C8',
        'bg-default':     '#FFFFFF',
        'bg-surface':     '#F5F5F5',
        'bg-inverse':     '#000000',
        'border-default': '#DCDDDD',
        'border-strong':  '#ADADAD',
        'border-focus':   '#2EA7E0',
        'filter-red':     '#FE3843',
        'filter-pink':    '#EF62C7',
        'filter-blue':    '#1A76FF',
        'filter-green':   '#98FE68',
        'filter-yellow':  '#FFDB1C',
        // dark UI
        black:  '#000000',
        'bg2':  '#111111',
        'bg3':  '#1A1A1A',
        dim:    '#444444',
        mid:    '#6E6E6E',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
      },
    },
  },
  plugins: [],
}
